services:
  - type: cron
    name: rossmann-scraper
    runtime: python
    schedule: "0 5 * * 1,4"
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper.py
    envVars:
      - key: SUPABASE_URL
        value: https://eifooaghbprllczieowj.supabase.co
      - key: SUPABASE_KEY
        sync: false
